/* A recursive-descent parser generated by greg 0.4.3 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
struct _GREG;
#define YYRULECOUNT 73

#include "ast.h"
#include "symbol.h"
#include "exception.h"

#define YYSTYPE ast_t *

#define YY_INPUT(buf, result, max_size, core)         \
{                                                     \
  int yyc = fgetc(stdin);                             \
  if (yyc == EOF) longjmp(exc, 2);                     \
  result = (EOF == yyc) ? 0 : (*(buf)= yyc, 1);       \
}

#ifndef YY_ALLOC
#define YY_ALLOC(N, D) malloc(N)
#endif
#ifndef YY_CALLOC
#define YY_CALLOC(N, S, D) calloc(N, S)
#endif
#ifndef YY_REALLOC
#define YY_REALLOC(B, N, D) realloc(B, N)
#endif
#ifndef YY_FREE
#define YY_FREE free
#endif
#ifndef YY_LOCAL
#define YY_LOCAL(T)     static T
#endif
#ifndef YY_ACTION
#define YY_ACTION(T)    static T
#endif
#ifndef YY_RULE
#define YY_RULE(T)      static T
#endif
#ifndef YY_PARSE
#define YY_PARSE(T)     T
#endif
#ifndef YY_NAME
#define YY_NAME(N) yy##N
#endif
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size, D)              \
  {                                                     \
    int yyc= getchar();                                 \
    result= (EOF == yyc) ? 0 : (*(buf)= yyc, 1);        \
    yyprintf((stderr, "<%c>", yyc));                  \
  }
#endif
#ifndef YY_BEGIN
#define YY_BEGIN        ( yytextpos= G->begin= G->pos, 1)
#endif
#ifndef YY_END
#define YY_END          ( G->end= G->pos, 1)
#endif
#ifdef YY_DEBUG
# define yyprintf(args) fprintf args
#else
# define yyprintf(args)
#endif
#ifndef YYSTYPE
#define YYSTYPE int
#endif
#ifndef YY_XTYPE
#define YY_XTYPE void *
#endif
#ifndef YY_XVAR
#define YY_XVAR yyxvar
#endif

#ifndef YY_STACK_SIZE
#define YY_STACK_SIZE 128
#endif

#ifndef YY_BUFFER_START_SIZE
#define YY_BUFFER_START_SIZE 1024
#endif

#ifndef YY_PART
#define yydata G->data
#define yy G->ss

struct _yythunk; // forward declaration
typedef void (*yyaction)(struct _GREG *G, char *yytext, int yyleng, struct _yythunk *thunkpos, YY_XTYPE YY_XVAR);
typedef struct _yythunk { int begin, end;  yyaction  action;  struct _yythunk *next; } yythunk;

typedef struct _GREG {
  char *buf;
  int buflen;
  int   offset;
  int   pos;
  int   limit;
  char *text;
  int   textlen;
  int   begin;
  int   end;
  yythunk *thunks;
  int   thunkslen;
  int thunkpos;
  YYSTYPE ss;
  YYSTYPE *val;
  YYSTYPE *vals;
  int valslen;
  YY_XTYPE data;
} GREG;

YY_LOCAL(int) yyrefill(GREG *G)
{
  int yyn;
  while (G->buflen - G->pos < 512)
    {
      G->buflen *= 2;
      G->buf= (char*)YY_REALLOC(G->buf, G->buflen, G->data);
    }
  YY_INPUT((G->buf + G->pos), yyn, (G->buflen - G->pos), G->data);
  if (!yyn) return 0;
  G->limit += yyn;
  return 1;
}

YY_LOCAL(int) yymatchDot(GREG *G)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  ++G->pos;
  return 1;
}

YY_LOCAL(int) yymatchChar(GREG *G, int c)
{
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  if ((unsigned char)G->buf[G->pos] == c)
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchChar(%c) @ %s\n", c, G->buf+G->pos));
  return 0;
}

YY_LOCAL(int) yymatchString(GREG *G, const char *s)
{
  int yysav= G->pos;
  while (*s)
    {
      if (G->pos >= G->limit && !yyrefill(G)) return 0;
      if (G->buf[G->pos] != *s)
        {
          G->pos= yysav;
          return 0;
        }
      ++s;
      ++G->pos;
    }
  return 1;
}

YY_LOCAL(int) yymatchClass(GREG *G, unsigned char *bits)
{
  int c;
  if (G->pos >= G->limit && !yyrefill(G)) return 0;
  c= (unsigned char)G->buf[G->pos];
  if (bits[c >> 3] & (1 << (c & 7)))
    {
      ++G->pos;
      yyprintf((stderr, "  ok   yymatchClass @ %s\n", G->buf+G->pos));
      return 1;
    }
  yyprintf((stderr, "  fail yymatchClass @ %s\n", G->buf+G->pos));
  return 0;
}

YY_LOCAL(void) yyDo(GREG *G, yyaction action, int begin, int end)
{
  while (G->thunkpos >= G->thunkslen)
    {
      G->thunkslen *= 2;
      G->thunks= (yythunk*)YY_REALLOC(G->thunks, sizeof(yythunk) * G->thunkslen, G->data);
    }
  G->thunks[G->thunkpos].begin=  begin;
  G->thunks[G->thunkpos].end=    end;
  G->thunks[G->thunkpos].action= action;
  ++G->thunkpos;
}

YY_LOCAL(int) yyText(GREG *G, int begin, int end)
{
  int yyleng= end - begin;
  if (yyleng <= 0)
    yyleng= 0;
  else
    {
      while (G->textlen < (yyleng - 1))
        {
          G->textlen *= 2;
          G->text= (char*)YY_REALLOC(G->text, G->textlen, G->data);
        }
      memcpy(G->text, G->buf + begin, yyleng);
    }
  G->text[yyleng]= '\0';
  return yyleng;
}

YY_LOCAL(void) yyDone(GREG *G)
{
  int pos;
  for (pos= 0; pos < G->thunkpos; ++pos)
    {
      yythunk *thunk= &G->thunks[pos];
      int yyleng= thunk->end ? yyText(G, thunk->begin, thunk->end) : thunk->begin;
      yyprintf((stderr, "DO [%d] %p %s\n", pos, thunk->action, G->text));
      thunk->action(G, G->text, yyleng, thunk, G->data);
    }
  G->thunkpos= 0;
}

YY_LOCAL(void) yyCommit(GREG *G)
{
  if ((G->limit -= G->pos))
    {
      memmove(G->buf, G->buf + G->pos, G->limit);
    }
  G->offset += G->pos;
  G->begin -= G->pos;
  G->end -= G->pos;
  G->pos= G->thunkpos= 0;
}

YY_LOCAL(int) yyAccept(GREG *G, int tp0)
{
  if (tp0)
    {
      fprintf(stderr, "accept denied at %d\n", tp0);
      return 0;
    }
  else
    {
      yyDone(G);
      yyCommit(G);
    }
  return 1;
}

YY_LOCAL(void) yyPush(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR) { G->val += count; }
YY_LOCAL(void) yyPop(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val -= count; }
YY_LOCAL(void) yySet(GREG *G, char *text, int count, yythunk *thunk, YY_XTYPE YY_XVAR)  { G->val[count]= G->ss; }

#endif /* YY_PART */

#define YYACCEPT        yyAccept(G, yythunkpos0)

YY_RULE(int) yy_Comment2(GREG *G); /* 73 */
YY_RULE(int) yy_Comment1(GREG *G); /* 72 */
YY_RULE(int) yy_Comment(GREG *G); /* 71 */
YY_RULE(int) yy_Space(GREG *G); /* 70 */
YY_RULE(int) yy_SlashQuotes(GREG *G); /* 69 */
YY_RULE(int) yy_Quotes(GREG *G); /* 68 */
YY_RULE(int) yy_Integer(GREG *G); /* 67 */
YY_RULE(int) yy_IdentCont(GREG *G); /* 66 */
YY_RULE(int) yy_IdentStart(GREG *G); /* 65 */
YY_RULE(int) yy_RParen(GREG *G); /* 64 */
YY_RULE(int) yy_LParen(GREG *G); /* 63 */
YY_RULE(int) yy_String(GREG *G); /* 62 */
YY_RULE(int) yy_IntConst(GREG *G); /* 61 */
YY_RULE(int) yy_Double(GREG *G); /* 60 */
YY_RULE(int) yy_Primary(GREG *G); /* 59 */
YY_RULE(int) yy_PostfixExp(GREG *G); /* 58 */
YY_RULE(int) yy_BitNot(GREG *G); /* 57 */
YY_RULE(int) yy_LogNot(GREG *G); /* 56 */
YY_RULE(int) yy_Decr(GREG *G); /* 55 */
YY_RULE(int) yy_Incr(GREG *G); /* 54 */
YY_RULE(int) yy_Mod(GREG *G); /* 53 */
YY_RULE(int) yy_Div(GREG *G); /* 52 */
YY_RULE(int) yy_Times(GREG *G); /* 51 */
YY_RULE(int) yy_UnaryExp(GREG *G); /* 50 */
YY_RULE(int) yy_Minus(GREG *G); /* 49 */
YY_RULE(int) yy_Plus(GREG *G); /* 48 */
YY_RULE(int) yy_Infix10(GREG *G); /* 47 */
YY_RULE(int) yy_Rsh(GREG *G); /* 46 */
YY_RULE(int) yy_Lsh(GREG *G); /* 45 */
YY_RULE(int) yy_Infix20(GREG *G); /* 44 */
YY_RULE(int) yy_GT(GREG *G); /* 43 */
YY_RULE(int) yy_LT(GREG *G); /* 42 */
YY_RULE(int) yy_GE(GREG *G); /* 41 */
YY_RULE(int) yy_LE(GREG *G); /* 40 */
YY_RULE(int) yy_Infix30(GREG *G); /* 39 */
YY_RULE(int) yy_NE(GREG *G); /* 38 */
YY_RULE(int) yy_EQ(GREG *G); /* 37 */
YY_RULE(int) yy_Infix40(GREG *G); /* 36 */
YY_RULE(int) yy_BitAnd(GREG *G); /* 35 */
YY_RULE(int) yy_Infix50(GREG *G); /* 34 */
YY_RULE(int) yy_BitXor(GREG *G); /* 33 */
YY_RULE(int) yy_Infix60(GREG *G); /* 32 */
YY_RULE(int) yy_BitOr(GREG *G); /* 31 */
YY_RULE(int) yy_Infix70(GREG *G); /* 30 */
YY_RULE(int) yy_LogAnd(GREG *G); /* 29 */
YY_RULE(int) yy_Infix80(GREG *G); /* 28 */
YY_RULE(int) yy_LogOr(GREG *G); /* 27 */
YY_RULE(int) yy_Infix90(GREG *G); /* 26 */
YY_RULE(int) yy_Infix100(GREG *G); /* 25 */
YY_RULE(int) yy_ShlEQ(GREG *G); /* 24 */
YY_RULE(int) yy_ShrEQ(GREG *G); /* 23 */
YY_RULE(int) yy_XorEQ(GREG *G); /* 22 */
YY_RULE(int) yy_OrEQ(GREG *G); /* 21 */
YY_RULE(int) yy_AndEQ(GREG *G); /* 20 */
YY_RULE(int) yy_ModEQ(GREG *G); /* 19 */
YY_RULE(int) yy_DivEQ(GREG *G); /* 18 */
YY_RULE(int) yy_TimesEQ(GREG *G); /* 17 */
YY_RULE(int) yy_MinusEQ(GREG *G); /* 16 */
YY_RULE(int) yy_PlusEQ(GREG *G); /* 15 */
YY_RULE(int) yy_AssignExp(GREG *G); /* 14 */
YY_RULE(int) yy_Equals(GREG *G); /* 13 */
YY_RULE(int) yy_Identifier(GREG *G); /* 12 */
YY_RULE(int) yy_Assignment(GREG *G); /* 11 */
YY_RULE(int) yy_Comma(GREG *G); /* 10 */
YY_RULE(int) yy_VarAssign(GREG *G); /* 9 */
YY_RULE(int) yy_Var(GREG *G); /* 8 */
YY_RULE(int) yy_Expression(GREG *G); /* 7 */
YY_RULE(int) yy_VarStmt(GREG *G); /* 6 */
YY_RULE(int) yy_Symtab(GREG *G); /* 5 */
YY_RULE(int) yy_EOL(GREG *G); /* 4 */
YY_RULE(int) yy_Statement(GREG *G); /* 3 */
YY_RULE(int) yy_Spacing(GREG *G); /* 2 */
YY_RULE(int) yy_start(GREG *G); /* 1 */

YY_ACTION(void) yy_1_Minus(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Minus\n"));
   yy = op_minus; ;
}
YY_ACTION(void) yy_1_Plus(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Plus\n"));
   yy = op_plus; ;
}
YY_ACTION(void) yy_1_Double(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Double\n"));
  
                 sym_t * sym = sym_lookup(yytext);
                 yy = ast_symbol(sym, AST_DOUBLE);
              ;
}
YY_ACTION(void) yy_1_String(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_String\n"));
  
                 sym_t * sym = sym_lookup(yytext);
                 yy = ast_symbol(sym, AST_STRING);
              ;
}
YY_ACTION(void) yy_1_IntConst(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_IntConst\n"));
  
                 sym_t * sym = sym_lookup(yytext);
                 yy = ast_symbol(sym, AST_INT);
              ;
}
YY_ACTION(void) yy_1_Identifier(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Identifier\n"));
  
                 sym_t * sym = sym_lookup(yytext);
                 yy = ast_symbol(sym, AST_IDENT);
              ;
}
YY_ACTION(void) yy_2_PostfixExp(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_2_PostfixExp\n"));
   yy = ast_unary(r, AST_POST_DEC); ;
#undef r
}
YY_ACTION(void) yy_1_PostfixExp(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_1_PostfixExp\n"));
   yy = ast_unary(r, AST_POST_INC); ;
#undef r
}
YY_ACTION(void) yy_2_Infix20(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define o G->val[-2]
#define r G->val[-3]
  yyprintf((stderr, "do yy_2_Infix20\n"));
   yy = r; ;
#undef s
#undef o
#undef r
}
YY_ACTION(void) yy_1_Infix20(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define o G->val[-2]
#define r G->val[-3]
  yyprintf((stderr, "do yy_1_Infix20\n"));
   r = ast_binary(r, s, o); ;
#undef s
#undef o
#undef r
}
YY_ACTION(void) yy_1_Assignment(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_1_Assignment\n"));
  
                 r->next = s;
                 yy = ast_unary(r, AST_ASSIGNMENT);
              ;
#undef s
#undef r
}
YY_ACTION(void) yy_2_VarStmt(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_2_VarStmt\n"));
  
                 r = ast_reverse(r);
                 yy = ast_unary(r, AST_VARASSIGN);
              ;
#undef s
#undef r
}
YY_ACTION(void) yy_1_VarStmt(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define s G->val[-1]
#define r G->val[-2]
  yyprintf((stderr, "do yy_1_VarStmt\n"));
  
                 s->next = r;
                 r = s;
              ;
#undef s
#undef r
}
YY_ACTION(void) yy_1_Statement(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
  yyprintf((stderr, "do yy_1_Statement\n"));
   print_sym_tab(); ;
}
YY_ACTION(void) yy_2_start(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_2_start\n"));
   root = NULL; printf("Syntax error\n"); ;
#undef r
}
YY_ACTION(void) yy_1_start(GREG *G, char *yytext, int yyleng, yythunk *thunk, YY_XTYPE YY_XVAR)
{
#define r G->val[-1]
  yyprintf((stderr, "do yy_1_start\n"));
   root = r; ;
#undef r
}

YY_RULE(int) yy_Comment2(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Comment2"));  if (!yymatchString(G, "/*")) goto l1;
  l2:;	
  {  int yypos3= G->pos, yythunkpos3= G->thunkpos;
  {  int yypos4= G->pos, yythunkpos4= G->thunkpos;  if (!yymatchString(G, "*/")) goto l4;  goto l3;
  l4:;	  G->pos= yypos4; G->thunkpos= yythunkpos4;
  }  if (!yymatchDot(G)) goto l3;  goto l2;
  l3:;	  G->pos= yypos3; G->thunkpos= yythunkpos3;
  }  if (!yymatchString(G, "*/")) goto l1;
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment2", G->buf+G->pos));
  return 1;
  l1:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment2", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Comment1(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Comment1"));  if (!yymatchString(G, "//")) goto l5;
  l6:;	
  {  int yypos7= G->pos, yythunkpos7= G->thunkpos;
  {  int yypos8= G->pos, yythunkpos8= G->thunkpos;  if (!yy_EOL(G)) { goto l8; }  goto l7;
  l8:;	  G->pos= yypos8; G->thunkpos= yythunkpos8;
  }  if (!yymatchDot(G)) goto l7;  goto l6;
  l7:;	  G->pos= yypos7; G->thunkpos= yythunkpos7;
  }  if (!yy_EOL(G)) { goto l5; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment1", G->buf+G->pos));
  return 1;
  l5:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment1", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Comment(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Comment"));
  {  int yypos10= G->pos, yythunkpos10= G->thunkpos;  if (!yy_Comment1(G)) { goto l11; }  goto l10;
  l11:;	  G->pos= yypos10; G->thunkpos= yythunkpos10;  if (!yy_Comment2(G)) { goto l9; }
  }
  l10:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Comment", G->buf+G->pos));
  return 1;
  l9:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Space(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Space"));
  {  int yypos13= G->pos, yythunkpos13= G->thunkpos;  if (!yymatchChar(G, ' ')) goto l14;  goto l13;
  l14:;	  G->pos= yypos13; G->thunkpos= yythunkpos13;  if (!yymatchChar(G, '\t')) goto l15;  goto l13;
  l15:;	  G->pos= yypos13; G->thunkpos= yythunkpos13;  if (!yy_EOL(G)) { goto l12; }
  }
  l13:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Space", G->buf+G->pos));
  return 1;
  l12:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Space", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_SlashQuotes(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "SlashQuotes"));  if (!yymatchString(G, "\\\"")) goto l16;
  yyprintf((stderr, "  ok   %s @ %s\n", "SlashQuotes", G->buf+G->pos));
  return 1;
  l16:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "SlashQuotes", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Quotes(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Quotes"));  if (!yymatchChar(G, '"')) goto l17;
  yyprintf((stderr, "  ok   %s @ %s\n", "Quotes", G->buf+G->pos));
  return 1;
  l17:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Quotes", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Integer(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Integer"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l18;
  {  int yypos19= G->pos, yythunkpos19= G->thunkpos;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\376\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l20;
  l21:;	
  {  int yypos22= G->pos, yythunkpos22= G->thunkpos;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l22;  goto l21;
  l22:;	  G->pos= yypos22; G->thunkpos= yythunkpos22;
  }  goto l19;
  l20:;	  G->pos= yypos19; G->thunkpos= yythunkpos19;  if (!yymatchChar(G, '0')) goto l18;
  }
  l19:;	  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l18;
  yyprintf((stderr, "  ok   %s @ %s\n", "Integer", G->buf+G->pos));
  return 1;
  l18:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Integer", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_IdentCont(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "IdentCont"));
  {  int yypos24= G->pos, yythunkpos24= G->thunkpos;  if (!yy_IdentStart(G)) { goto l25; }  goto l24;
  l25:;	  G->pos= yypos24; G->thunkpos= yythunkpos24;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l23;
  }
  l24:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "IdentCont", G->buf+G->pos));
  return 1;
  l23:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IdentCont", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_IdentStart(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "IdentStart"));  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\000\000\376\377\377\207\376\377\377\007\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l26;
  yyprintf((stderr, "  ok   %s @ %s\n", "IdentStart", G->buf+G->pos));
  return 1;
  l26:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IdentStart", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_RParen(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "RParen"));  if (!yymatchChar(G, ')')) goto l27;  if (!yy_Spacing(G)) { goto l27; }
  yyprintf((stderr, "  ok   %s @ %s\n", "RParen", G->buf+G->pos));
  return 1;
  l27:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "RParen", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LParen(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LParen"));  if (!yymatchChar(G, '(')) goto l28;  if (!yy_Spacing(G)) { goto l28; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LParen", G->buf+G->pos));
  return 1;
  l28:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LParen", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_String(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "String"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l29;  if (!yy_Quotes(G)) { goto l29; }
  l30:;	
  {  int yypos31= G->pos, yythunkpos31= G->thunkpos;
  {  int yypos32= G->pos, yythunkpos32= G->thunkpos;  if (!yy_SlashQuotes(G)) { goto l33; }  goto l32;
  l33:;	  G->pos= yypos32; G->thunkpos= yythunkpos32;
  {  int yypos34= G->pos, yythunkpos34= G->thunkpos;  if (!yy_Quotes(G)) { goto l34; }  goto l31;
  l34:;	  G->pos= yypos34; G->thunkpos= yythunkpos34;
  }  if (!yymatchDot(G)) goto l31;
  }
  l32:;	  goto l30;
  l31:;	  G->pos= yypos31; G->thunkpos= yythunkpos31;
  }  if (!yy_Quotes(G)) { goto l29; }  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l29;  if (!yy_Spacing(G)) { goto l29; }  yyDo(G, yy_1_String, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "String", G->buf+G->pos));
  return 1;
  l29:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "String", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_IntConst(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "IntConst"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l35;  if (!yy_Integer(G)) { goto l35; }
  {  int yypos36= G->pos, yythunkpos36= G->thunkpos;  if (!yymatchChar(G, 'u')) goto l36;  goto l37;
  l36:;	  G->pos= yypos36; G->thunkpos= yythunkpos36;
  }
  l37:;	
  {  int yypos38= G->pos, yythunkpos38= G->thunkpos;
  {  int yypos40= G->pos, yythunkpos40= G->thunkpos;  if (!yymatchChar(G, 'b')) goto l41;  goto l40;
  l41:;	  G->pos= yypos40; G->thunkpos= yythunkpos40;  if (!yymatchChar(G, 'w')) goto l42;  goto l40;
  l42:;	  G->pos= yypos40; G->thunkpos= yythunkpos40;  if (!yymatchChar(G, 'd')) goto l43;  goto l40;
  l43:;	  G->pos= yypos40; G->thunkpos= yythunkpos40;  if (!yymatchChar(G, 'q')) goto l38;
  }
  l40:;	  goto l39;
  l38:;	  G->pos= yypos38; G->thunkpos= yythunkpos38;
  }
  l39:;	  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l35;  if (!yy_Spacing(G)) { goto l35; }  yyDo(G, yy_1_IntConst, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "IntConst", G->buf+G->pos));
  return 1;
  l35:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "IntConst", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Double(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Double"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l44;  if (!yy_Integer(G)) { goto l44; }  if (!yymatchChar(G, '.')) goto l44;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l44;
  l45:;	
  {  int yypos46= G->pos, yythunkpos46= G->thunkpos;  if (!yymatchClass(G, (unsigned char *)"\000\000\000\000\000\000\377\003\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000")) goto l46;  goto l45;
  l46:;	  G->pos= yypos46; G->thunkpos= yythunkpos46;
  }
  {  int yypos47= G->pos, yythunkpos47= G->thunkpos;
  {  int yypos49= G->pos, yythunkpos49= G->thunkpos;  if (!yymatchChar(G, 'e')) goto l50;  goto l49;
  l50:;	  G->pos= yypos49; G->thunkpos= yythunkpos49;  if (!yymatchChar(G, 'E')) goto l47;
  }
  l49:;	
  {  int yypos51= G->pos, yythunkpos51= G->thunkpos;  if (!yymatchChar(G, '-')) goto l51;  goto l52;
  l51:;	  G->pos= yypos51; G->thunkpos= yythunkpos51;
  }
  l52:;	  if (!yy_Integer(G)) { goto l47; }  goto l48;
  l47:;	  G->pos= yypos47; G->thunkpos= yythunkpos47;
  }
  l48:;	
  {  int yypos53= G->pos, yythunkpos53= G->thunkpos;
  {  int yypos55= G->pos, yythunkpos55= G->thunkpos;  if (!yymatchChar(G, 'f')) goto l56;  goto l55;
  l56:;	  G->pos= yypos55; G->thunkpos= yythunkpos55;  if (!yymatchChar(G, 'd')) goto l53;
  }
  l55:;	  goto l54;
  l53:;	  G->pos= yypos53; G->thunkpos= yythunkpos53;
  }
  l54:;	  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l44;  if (!yy_Spacing(G)) { goto l44; }  yyDo(G, yy_1_Double, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Double", G->buf+G->pos));
  return 1;
  l44:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Double", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Primary(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Primary"));
  {  int yypos58= G->pos, yythunkpos58= G->thunkpos;  if (!yy_Identifier(G)) { goto l59; }  goto l58;
  l59:;	  G->pos= yypos58; G->thunkpos= yythunkpos58;  if (!yy_Double(G)) { goto l60; }  goto l58;
  l60:;	  G->pos= yypos58; G->thunkpos= yythunkpos58;  if (!yy_IntConst(G)) { goto l61; }  goto l58;
  l61:;	  G->pos= yypos58; G->thunkpos= yythunkpos58;  if (!yy_String(G)) { goto l62; }  goto l58;
  l62:;	  G->pos= yypos58; G->thunkpos= yythunkpos58;  if (!yy_LParen(G)) { goto l57; }  if (!yy_Expression(G)) { goto l57; }  if (!yy_RParen(G)) { goto l57; }
  }
  l58:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Primary", G->buf+G->pos));
  return 1;
  l57:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Primary", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_PostfixExp(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "PostfixExp"));
  {  int yypos64= G->pos, yythunkpos64= G->thunkpos;  if (!yy_Identifier(G)) { goto l65; }  yyDo(G, yySet, -1, 0);  if (!yy_Incr(G)) { goto l65; }  yyDo(G, yy_1_PostfixExp, yytextpos?yytextpos:G->begin, G->end);  goto l64;
  l65:;	  G->pos= yypos64; G->thunkpos= yythunkpos64;  if (!yy_Identifier(G)) { goto l66; }  yyDo(G, yySet, -1, 0);  if (!yy_Decr(G)) { goto l66; }  yyDo(G, yy_2_PostfixExp, yytextpos?yytextpos:G->begin, G->end);  goto l64;
  l66:;	  G->pos= yypos64; G->thunkpos= yythunkpos64;  if (!yy_Primary(G)) { goto l63; }
  }
  l64:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "PostfixExp", G->buf+G->pos));  yyDo(G, yyPop, 1, 0);
  return 1;
  l63:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PostfixExp", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BitNot(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BitNot"));  if (!yymatchChar(G, '~')) goto l67;  if (!yy_Spacing(G)) { goto l67; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BitNot", G->buf+G->pos));
  return 1;
  l67:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BitNot", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LogNot(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LogNot"));  if (!yymatchChar(G, '!')) goto l68;  if (!yy_Spacing(G)) { goto l68; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LogNot", G->buf+G->pos));
  return 1;
  l68:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogNot", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Decr(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Decr"));  if (!yymatchString(G, "--")) goto l69;  if (!yy_Spacing(G)) { goto l69; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Decr", G->buf+G->pos));
  return 1;
  l69:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Decr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Incr(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Incr"));  if (!yymatchString(G, "++")) goto l70;  if (!yy_Spacing(G)) { goto l70; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Incr", G->buf+G->pos));
  return 1;
  l70:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Incr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Mod(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Mod"));  if (!yymatchChar(G, '%')) goto l71;  if (!yy_Spacing(G)) { goto l71; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Mod", G->buf+G->pos));
  return 1;
  l71:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Mod", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Div(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Div"));  if (!yymatchChar(G, '/')) goto l72;  if (!yy_Spacing(G)) { goto l72; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Div", G->buf+G->pos));
  return 1;
  l72:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Div", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Times(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Times"));  if (!yymatchChar(G, '*')) goto l73;  if (!yy_Spacing(G)) { goto l73; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Times", G->buf+G->pos));
  return 1;
  l73:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Times", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_UnaryExp(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "UnaryExp"));
  {  int yypos75= G->pos, yythunkpos75= G->thunkpos;  if (!yy_Incr(G)) { goto l76; }  if (!yy_Identifier(G)) { goto l76; }  goto l75;
  l76:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_Decr(G)) { goto l77; }  if (!yy_Identifier(G)) { goto l77; }  goto l75;
  l77:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_Plus(G)) { goto l78; }  if (!yy_UnaryExp(G)) { goto l78; }  goto l75;
  l78:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_Minus(G)) { goto l79; }  if (!yy_UnaryExp(G)) { goto l79; }  goto l75;
  l79:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_LogNot(G)) { goto l80; }  if (!yy_UnaryExp(G)) { goto l80; }  goto l75;
  l80:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_BitNot(G)) { goto l81; }  if (!yy_UnaryExp(G)) { goto l81; }  goto l75;
  l81:;	  G->pos= yypos75; G->thunkpos= yythunkpos75;  if (!yy_PostfixExp(G)) { goto l74; }
  }
  l75:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "UnaryExp", G->buf+G->pos));
  return 1;
  l74:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "UnaryExp", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Minus(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Minus"));  if (!yymatchChar(G, '-')) goto l82;  if (!yy_Spacing(G)) { goto l82; }  yyDo(G, yy_1_Minus, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Minus", G->buf+G->pos));
  return 1;
  l82:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Minus", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Plus(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Plus"));  if (!yymatchChar(G, '+')) goto l83;  if (!yy_Spacing(G)) { goto l83; }  yyDo(G, yy_1_Plus, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Plus", G->buf+G->pos));
  return 1;
  l83:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Plus", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix10(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix10"));  if (!yy_UnaryExp(G)) { goto l84; }
  l85:;	
  {  int yypos86= G->pos, yythunkpos86= G->thunkpos;
  {  int yypos87= G->pos, yythunkpos87= G->thunkpos;  if (!yy_Times(G)) { goto l88; }  goto l87;
  l88:;	  G->pos= yypos87; G->thunkpos= yythunkpos87;  if (!yy_Div(G)) { goto l89; }  goto l87;
  l89:;	  G->pos= yypos87; G->thunkpos= yythunkpos87;  if (!yy_Mod(G)) { goto l86; }
  }
  l87:;	  if (!yy_UnaryExp(G)) { goto l86; }  goto l85;
  l86:;	  G->pos= yypos86; G->thunkpos= yythunkpos86;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix10", G->buf+G->pos));
  return 1;
  l84:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix10", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Rsh(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Rsh"));  if (!yymatchString(G, ">>")) goto l90;  if (!yy_Spacing(G)) { goto l90; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Rsh", G->buf+G->pos));
  return 1;
  l90:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Rsh", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Lsh(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Lsh"));  if (!yymatchString(G, "<<")) goto l91;  if (!yy_Spacing(G)) { goto l91; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Lsh", G->buf+G->pos));
  return 1;
  l91:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Lsh", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix20(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 3, 0);
  yyprintf((stderr, "%s\n", "Infix20"));  if (!yy_Infix10(G)) { goto l92; }  yyDo(G, yySet, -3, 0);
  l93:;	
  {  int yypos94= G->pos, yythunkpos94= G->thunkpos;
  {  int yypos95= G->pos, yythunkpos95= G->thunkpos;  if (!yy_Plus(G)) { goto l96; }  yyDo(G, yySet, -2, 0);  goto l95;
  l96:;	  G->pos= yypos95; G->thunkpos= yythunkpos95;  if (!yy_Minus(G)) { goto l94; }  yyDo(G, yySet, -2, 0);
  }
  l95:;	  if (!yy_Infix10(G)) { goto l94; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_Infix20, yytextpos?yytextpos:G->begin, G->end);  goto l93;
  l94:;	  G->pos= yypos94; G->thunkpos= yythunkpos94;
  }  yyDo(G, yy_2_Infix20, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix20", G->buf+G->pos));  yyDo(G, yyPop, 3, 0);
  return 1;
  l92:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix20", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_GT(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "GT"));  if (!yymatchChar(G, '>')) goto l97;  if (!yy_Spacing(G)) { goto l97; }
  yyprintf((stderr, "  ok   %s @ %s\n", "GT", G->buf+G->pos));
  return 1;
  l97:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GT", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LT(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LT"));  if (!yymatchChar(G, '<')) goto l98;  if (!yy_Spacing(G)) { goto l98; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LT", G->buf+G->pos));
  return 1;
  l98:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LT", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_GE(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "GE"));  if (!yymatchString(G, ">=")) goto l99;  if (!yy_Spacing(G)) { goto l99; }
  yyprintf((stderr, "  ok   %s @ %s\n", "GE", G->buf+G->pos));
  return 1;
  l99:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "GE", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LE(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LE"));  if (!yymatchString(G, "<=")) goto l100;  if (!yy_Spacing(G)) { goto l100; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LE", G->buf+G->pos));
  return 1;
  l100:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LE", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix30(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix30"));  if (!yy_Infix20(G)) { goto l101; }
  l102:;	
  {  int yypos103= G->pos, yythunkpos103= G->thunkpos;
  {  int yypos104= G->pos, yythunkpos104= G->thunkpos;  if (!yy_Lsh(G)) { goto l105; }  goto l104;
  l105:;	  G->pos= yypos104; G->thunkpos= yythunkpos104;  if (!yy_Rsh(G)) { goto l103; }
  }
  l104:;	  if (!yy_Infix20(G)) { goto l103; }  goto l102;
  l103:;	  G->pos= yypos103; G->thunkpos= yythunkpos103;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix30", G->buf+G->pos));
  return 1;
  l101:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix30", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_NE(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "NE"));  if (!yymatchString(G, "!=")) goto l106;  if (!yy_Spacing(G)) { goto l106; }
  yyprintf((stderr, "  ok   %s @ %s\n", "NE", G->buf+G->pos));
  return 1;
  l106:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "NE", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_EQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "EQ"));  if (!yymatchString(G, "==")) goto l107;  if (!yy_Spacing(G)) { goto l107; }
  yyprintf((stderr, "  ok   %s @ %s\n", "EQ", G->buf+G->pos));
  return 1;
  l107:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix40(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix40"));  if (!yy_Infix30(G)) { goto l108; }
  l109:;	
  {  int yypos110= G->pos, yythunkpos110= G->thunkpos;
  {  int yypos111= G->pos, yythunkpos111= G->thunkpos;  if (!yy_LE(G)) { goto l112; }  goto l111;
  l112:;	  G->pos= yypos111; G->thunkpos= yythunkpos111;  if (!yy_GE(G)) { goto l113; }  goto l111;
  l113:;	  G->pos= yypos111; G->thunkpos= yythunkpos111;  if (!yy_LT(G)) { goto l114; }  goto l111;
  l114:;	  G->pos= yypos111; G->thunkpos= yythunkpos111;  if (!yy_GT(G)) { goto l110; }
  }
  l111:;	  if (!yy_Infix30(G)) { goto l110; }  goto l109;
  l110:;	  G->pos= yypos110; G->thunkpos= yythunkpos110;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix40", G->buf+G->pos));
  return 1;
  l108:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix40", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BitAnd(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BitAnd"));  if (!yymatchChar(G, '&')) goto l115;  if (!yy_Spacing(G)) { goto l115; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BitAnd", G->buf+G->pos));
  return 1;
  l115:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BitAnd", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix50(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix50"));  if (!yy_Infix40(G)) { goto l116; }
  l117:;	
  {  int yypos118= G->pos, yythunkpos118= G->thunkpos;
  {  int yypos119= G->pos, yythunkpos119= G->thunkpos;  if (!yy_EQ(G)) { goto l120; }  goto l119;
  l120:;	  G->pos= yypos119; G->thunkpos= yythunkpos119;  if (!yy_NE(G)) { goto l118; }
  }
  l119:;	  if (!yy_Infix40(G)) { goto l118; }  goto l117;
  l118:;	  G->pos= yypos118; G->thunkpos= yythunkpos118;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix50", G->buf+G->pos));
  return 1;
  l116:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix50", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BitXor(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BitXor"));  if (!yymatchString(G, "^|")) goto l121;  if (!yy_Spacing(G)) { goto l121; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BitXor", G->buf+G->pos));
  return 1;
  l121:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BitXor", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix60(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix60"));  if (!yy_Infix50(G)) { goto l122; }
  l123:;	
  {  int yypos124= G->pos, yythunkpos124= G->thunkpos;  if (!yy_BitAnd(G)) { goto l124; }  if (!yy_Infix50(G)) { goto l124; }  goto l123;
  l124:;	  G->pos= yypos124; G->thunkpos= yythunkpos124;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix60", G->buf+G->pos));
  return 1;
  l122:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix60", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_BitOr(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "BitOr"));  if (!yymatchChar(G, '|')) goto l125;  if (!yy_Spacing(G)) { goto l125; }
  yyprintf((stderr, "  ok   %s @ %s\n", "BitOr", G->buf+G->pos));
  return 1;
  l125:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "BitOr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix70(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix70"));  if (!yy_Infix60(G)) { goto l126; }
  l127:;	
  {  int yypos128= G->pos, yythunkpos128= G->thunkpos;  if (!yy_BitXor(G)) { goto l128; }  if (!yy_Infix60(G)) { goto l128; }  goto l127;
  l128:;	  G->pos= yypos128; G->thunkpos= yythunkpos128;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix70", G->buf+G->pos));
  return 1;
  l126:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix70", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LogAnd(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LogAnd"));  if (!yymatchString(G, "&&")) goto l129;  if (!yy_Spacing(G)) { goto l129; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LogAnd", G->buf+G->pos));
  return 1;
  l129:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogAnd", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix80(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix80"));  if (!yy_Infix70(G)) { goto l130; }
  l131:;	
  {  int yypos132= G->pos, yythunkpos132= G->thunkpos;  if (!yy_BitOr(G)) { goto l132; }  if (!yy_Infix70(G)) { goto l132; }  goto l131;
  l132:;	  G->pos= yypos132; G->thunkpos= yythunkpos132;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix80", G->buf+G->pos));
  return 1;
  l130:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix80", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_LogOr(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "LogOr"));  if (!yymatchString(G, "||")) goto l133;  if (!yy_Spacing(G)) { goto l133; }
  yyprintf((stderr, "  ok   %s @ %s\n", "LogOr", G->buf+G->pos));
  return 1;
  l133:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "LogOr", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix90(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix90"));  if (!yy_Infix80(G)) { goto l134; }
  l135:;	
  {  int yypos136= G->pos, yythunkpos136= G->thunkpos;  if (!yy_LogAnd(G)) { goto l136; }  if (!yy_Infix80(G)) { goto l136; }  goto l135;
  l136:;	  G->pos= yypos136; G->thunkpos= yythunkpos136;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix90", G->buf+G->pos));
  return 1;
  l134:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix90", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Infix100(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Infix100"));  if (!yy_Infix90(G)) { goto l137; }
  l138:;	
  {  int yypos139= G->pos, yythunkpos139= G->thunkpos;  if (!yy_LogOr(G)) { goto l139; }  if (!yy_Infix90(G)) { goto l139; }  goto l138;
  l139:;	  G->pos= yypos139; G->thunkpos= yythunkpos139;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Infix100", G->buf+G->pos));
  return 1;
  l137:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Infix100", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_ShlEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "ShlEQ"));  if (!yymatchString(G, "<<=")) goto l140;  if (!yy_Spacing(G)) { goto l140; }
  yyprintf((stderr, "  ok   %s @ %s\n", "ShlEQ", G->buf+G->pos));
  return 1;
  l140:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ShlEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_ShrEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "ShrEQ"));  if (!yymatchString(G, ">>=")) goto l141;  if (!yy_Spacing(G)) { goto l141; }
  yyprintf((stderr, "  ok   %s @ %s\n", "ShrEQ", G->buf+G->pos));
  return 1;
  l141:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ShrEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_XorEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "XorEQ"));  if (!yymatchString(G, "^|=")) goto l142;  if (!yy_Spacing(G)) { goto l142; }
  yyprintf((stderr, "  ok   %s @ %s\n", "XorEQ", G->buf+G->pos));
  return 1;
  l142:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "XorEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_OrEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "OrEQ"));  if (!yymatchString(G, "|=")) goto l143;  if (!yy_Spacing(G)) { goto l143; }
  yyprintf((stderr, "  ok   %s @ %s\n", "OrEQ", G->buf+G->pos));
  return 1;
  l143:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "OrEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AndEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AndEQ"));  if (!yymatchString(G, "&=")) goto l144;  if (!yy_Spacing(G)) { goto l144; }
  yyprintf((stderr, "  ok   %s @ %s\n", "AndEQ", G->buf+G->pos));
  return 1;
  l144:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AndEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_ModEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "ModEQ"));  if (!yymatchString(G, "%=")) goto l145;  if (!yy_Spacing(G)) { goto l145; }
  yyprintf((stderr, "  ok   %s @ %s\n", "ModEQ", G->buf+G->pos));
  return 1;
  l145:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "ModEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_DivEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "DivEQ"));  if (!yymatchString(G, "/=")) goto l146;  if (!yy_Spacing(G)) { goto l146; }
  yyprintf((stderr, "  ok   %s @ %s\n", "DivEQ", G->buf+G->pos));
  return 1;
  l146:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "DivEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_TimesEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "TimesEQ"));  if (!yymatchString(G, "*=")) goto l147;  if (!yy_Spacing(G)) { goto l147; }
  yyprintf((stderr, "  ok   %s @ %s\n", "TimesEQ", G->buf+G->pos));
  return 1;
  l147:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "TimesEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_MinusEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "MinusEQ"));  if (!yymatchString(G, "-=")) goto l148;  if (!yy_Spacing(G)) { goto l148; }
  yyprintf((stderr, "  ok   %s @ %s\n", "MinusEQ", G->buf+G->pos));
  return 1;
  l148:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "MinusEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_PlusEQ(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "PlusEQ"));  if (!yymatchString(G, "+=")) goto l149;  if (!yy_Spacing(G)) { goto l149; }
  yyprintf((stderr, "  ok   %s @ %s\n", "PlusEQ", G->buf+G->pos));
  return 1;
  l149:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "PlusEQ", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_AssignExp(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "AssignExp"));
  {  int yypos151= G->pos, yythunkpos151= G->thunkpos;  if (!yy_Assignment(G)) { goto l152; }  goto l151;
  l152:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l153; }  if (!yy_PlusEQ(G)) { goto l153; }  if (!yy_AssignExp(G)) { goto l153; }  goto l151;
  l153:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l154; }  if (!yy_MinusEQ(G)) { goto l154; }  if (!yy_AssignExp(G)) { goto l154; }  goto l151;
  l154:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l155; }  if (!yy_TimesEQ(G)) { goto l155; }  if (!yy_AssignExp(G)) { goto l155; }  goto l151;
  l155:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l156; }  if (!yy_DivEQ(G)) { goto l156; }  if (!yy_AssignExp(G)) { goto l156; }  goto l151;
  l156:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l157; }  if (!yy_ModEQ(G)) { goto l157; }  if (!yy_AssignExp(G)) { goto l157; }  goto l151;
  l157:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l158; }  if (!yy_AndEQ(G)) { goto l158; }  if (!yy_AssignExp(G)) { goto l158; }  goto l151;
  l158:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l159; }  if (!yy_OrEQ(G)) { goto l159; }  if (!yy_AssignExp(G)) { goto l159; }  goto l151;
  l159:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l160; }  if (!yy_XorEQ(G)) { goto l160; }  if (!yy_AssignExp(G)) { goto l160; }  goto l151;
  l160:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l161; }  if (!yy_ShrEQ(G)) { goto l161; }  if (!yy_AssignExp(G)) { goto l161; }  goto l151;
  l161:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Identifier(G)) { goto l162; }  if (!yy_ShlEQ(G)) { goto l162; }  if (!yy_AssignExp(G)) { goto l162; }  goto l151;
  l162:;	  G->pos= yypos151; G->thunkpos= yythunkpos151;  if (!yy_Infix100(G)) { goto l150; }
  }
  l151:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "AssignExp", G->buf+G->pos));
  return 1;
  l150:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "AssignExp", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Equals(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Equals"));  if (!yymatchChar(G, '=')) goto l163;  if (!yy_Spacing(G)) { goto l163; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Equals", G->buf+G->pos));
  return 1;
  l163:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Equals", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Identifier(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Identifier"));  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_BEGIN)) goto l164;  if (!yy_IdentStart(G)) { goto l164; }
  l165:;	
  {  int yypos166= G->pos, yythunkpos166= G->thunkpos;  if (!yy_IdentCont(G)) { goto l166; }  goto l165;
  l166:;	  G->pos= yypos166; G->thunkpos= yythunkpos166;
  }  yyText(G, yytextpos?yytextpos:G->begin, G->end);  if (!(YY_END)) goto l164;  if (!yy_Spacing(G)) { goto l164; }  yyDo(G, yy_1_Identifier, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Identifier", G->buf+G->pos));
  return 1;
  l164:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Identifier", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Assignment(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "Assignment"));  if (!yy_Identifier(G)) { goto l167; }  yyDo(G, yySet, -2, 0);  if (!yy_Equals(G)) { goto l167; }  if (!yy_AssignExp(G)) { goto l167; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_Assignment, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "Assignment", G->buf+G->pos));  yyDo(G, yyPop, 2, 0);
  return 1;
  l167:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Assignment", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Comma(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Comma"));  if (!yymatchChar(G, ',')) goto l168;  if (!yy_Spacing(G)) { goto l168; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Comma", G->buf+G->pos));
  return 1;
  l168:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Comma", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_VarAssign(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "VarAssign"));
  {  int yypos170= G->pos, yythunkpos170= G->thunkpos;  if (!yy_Assignment(G)) { goto l171; }  goto l170;
  l171:;	  G->pos= yypos170; G->thunkpos= yythunkpos170;  if (!yy_Identifier(G)) { goto l169; }
  }
  l170:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "VarAssign", G->buf+G->pos));
  return 1;
  l169:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VarAssign", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Var(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Var"));  if (!yymatchString(G, "var")) goto l172;  if (!yy_Spacing(G)) { goto l172; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Var", G->buf+G->pos));
  return 1;
  l172:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Var", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Expression(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Expression"));  if (!yy_AssignExp(G)) { goto l173; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Expression", G->buf+G->pos));
  return 1;
  l173:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Expression", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_VarStmt(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 2, 0);
  yyprintf((stderr, "%s\n", "VarStmt"));  if (!yy_Var(G)) { goto l174; }  if (!yy_VarAssign(G)) { goto l174; }  yyDo(G, yySet, -2, 0);
  l175:;	
  {  int yypos176= G->pos, yythunkpos176= G->thunkpos;  if (!yy_Comma(G)) { goto l176; }  if (!yy_VarAssign(G)) { goto l176; }  yyDo(G, yySet, -1, 0);  yyDo(G, yy_1_VarStmt, yytextpos?yytextpos:G->begin, G->end);  goto l175;
  l176:;	  G->pos= yypos176; G->thunkpos= yythunkpos176;
  }  yyDo(G, yy_2_VarStmt, yytextpos?yytextpos:G->begin, G->end);
  yyprintf((stderr, "  ok   %s @ %s\n", "VarStmt", G->buf+G->pos));  yyDo(G, yyPop, 2, 0);
  return 1;
  l174:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "VarStmt", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Symtab(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Symtab"));  if (!yymatchString(G, "symtab")) goto l177;  if (!yy_Spacing(G)) { goto l177; }
  yyprintf((stderr, "  ok   %s @ %s\n", "Symtab", G->buf+G->pos));
  return 1;
  l177:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Symtab", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_EOL(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "EOL"));
  {  int yypos179= G->pos, yythunkpos179= G->thunkpos;  if (!yymatchString(G, "\r\n")) goto l180;  goto l179;
  l180:;	  G->pos= yypos179; G->thunkpos= yythunkpos179;  if (!yymatchChar(G, '\n')) goto l181;  goto l179;
  l181:;	  G->pos= yypos179; G->thunkpos= yythunkpos179;  if (!yymatchChar(G, '\r')) goto l178;
  }
  l179:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "EOL", G->buf+G->pos));
  return 1;
  l178:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "EOL", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Statement(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;
  yyprintf((stderr, "%s\n", "Statement"));
  {  int yypos183= G->pos, yythunkpos183= G->thunkpos;  if (!yy_Symtab(G)) { goto l184; }  yyDo(G, yy_1_Statement, yytextpos?yytextpos:G->begin, G->end);  goto l183;
  l184:;	  G->pos= yypos183; G->thunkpos= yythunkpos183;  if (!yy_VarStmt(G)) { goto l185; }  goto l183;
  l185:;	  G->pos= yypos183; G->thunkpos= yythunkpos183;  if (!yy_Expression(G)) { goto l182; }
  }
  l183:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "Statement", G->buf+G->pos));
  return 1;
  l182:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "Statement", G->buf+G->pos));
  return 0;
}
YY_RULE(int) yy_Spacing(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;

  yyprintf((stderr, "%s\n", "Spacing"));
  l187:;	
  {  int yypos188= G->pos, yythunkpos188= G->thunkpos;
  {  int yypos189= G->pos, yythunkpos189= G->thunkpos;  if (!yy_Space(G)) { goto l190; }  goto l189;
  l190:;	  G->pos= yypos189; G->thunkpos= yythunkpos189;  if (!yy_Comment(G)) { goto l188; }
  }
  l189:;	  goto l187;
  l188:;	  G->pos= yypos188; G->thunkpos= yythunkpos188;
  }
  yyprintf((stderr, "  ok   %s @ %s\n", "Spacing", G->buf+G->pos));
  return 1;
}
YY_RULE(int) yy_start(GREG *G)
{  int yytextpos = 0; yytextpos=yytextpos;
  int yypos0= G->pos, yythunkpos0= G->thunkpos;  yyDo(G, yyPush, 1, 0);
  yyprintf((stderr, "%s\n", "start"));
  {  int yypos192= G->pos, yythunkpos192= G->thunkpos;  if (!yy_Spacing(G)) { goto l193; }  if (!yy_Statement(G)) { goto l193; }  yyDo(G, yySet, -1, 0);  if (!yymatchChar(G, ';')) goto l193;  yyDo(G, yy_1_start, yytextpos?yytextpos:G->begin, G->end);  goto l192;
  l193:;	  G->pos= yypos192; G->thunkpos= yythunkpos192;
  l194:;	
  {  int yypos195= G->pos, yythunkpos195= G->thunkpos;
  {  int yypos196= G->pos, yythunkpos196= G->thunkpos;  if (!yy_EOL(G)) { goto l196; }  goto l195;
  l196:;	  G->pos= yypos196; G->thunkpos= yythunkpos196;
  }  if (!yymatchDot(G)) goto l195;  goto l194;
  l195:;	  G->pos= yypos195; G->thunkpos= yythunkpos195;
  }  if (!yy_EOL(G)) { goto l191; }  yyDo(G, yy_2_start, yytextpos?yytextpos:G->begin, G->end);
  }
  l192:;	
  yyprintf((stderr, "  ok   %s @ %s\n", "start", G->buf+G->pos));  yyDo(G, yyPop, 1, 0);
  return 1;
  l191:;	  G->pos= yypos0; G->thunkpos= yythunkpos0;
  yyprintf((stderr, "  fail %s @ %s\n", "start", G->buf+G->pos));
  return 0;
}

#ifndef YY_PART

typedef int (*yyrule)(GREG *G);

YY_PARSE(int) YY_NAME(parse_from)(GREG *G, yyrule yystart)
{
  int yyok;
  if (!G->buflen)
    {
      G->buflen= YY_BUFFER_START_SIZE;
      G->buf= (char*)YY_ALLOC(G->buflen, G->data);
      G->textlen= YY_BUFFER_START_SIZE;
      G->text= (char*)YY_ALLOC(G->textlen, G->data);
      G->thunkslen= YY_STACK_SIZE;
      G->thunks= (yythunk*)YY_ALLOC(sizeof(yythunk) * G->thunkslen, G->data);
      G->valslen= YY_STACK_SIZE;
      G->vals= (YYSTYPE*)YY_ALLOC(sizeof(YYSTYPE) * G->valslen, G->data);
      G->begin= G->end= G->pos= G->limit= G->thunkpos= 0;
    }
  G->pos = 0;
  G->begin= G->end= G->pos;
  G->thunkpos= 0;
  G->val= G->vals;
  yyok= yystart(G);
  if (yyok) yyDone(G);
  yyCommit(G);
  return yyok;
  (void)yyrefill;
  (void)yymatchDot;
  (void)yymatchChar;
  (void)yymatchString;
  (void)yymatchClass;
  (void)yyDo;
  (void)yyText;
  (void)yyDone;
  (void)yyCommit;
  (void)yyAccept;
  (void)yyPush;
  (void)yyPop;
  (void)yySet;
}

YY_PARSE(int) YY_NAME(parse)(GREG *G)
{
  return YY_NAME(parse_from)(G, yy_start);
}

YY_PARSE(void) YY_NAME(init)(GREG *G)
{
    memset(G, 0, sizeof(GREG));
}
YY_PARSE(void) YY_NAME(deinit)(GREG *G)
{
    if (G->buf) YY_FREE(G->buf);
    if (G->text) YY_FREE(G->text);
    if (G->thunks) YY_FREE(G->thunks);
    if (G->vals) YY_FREE(G->vals);
}
YY_PARSE(GREG *) YY_NAME(parse_new)(YY_XTYPE data)
{
  GREG *G = (GREG *)YY_CALLOC(1, sizeof(GREG), G->data);
  G->data = data;
  return G;
}

YY_PARSE(void) YY_NAME(parse_free)(GREG *G)
{
  YY_NAME(deinit)(G);
  YY_FREE(G);
}

#endif
